### ISSUE TITLE
Clipboard contains Pagecontent

### ISSUE THREAD

**Issue by Bestora** [jschx/uguush#30]
My Clipboard:

Uguu.se &middot; Temp File Hosting                                                 $( document ).ready(function(){             $(".button-collapse").sideNav();         })                                                                         Uguu.se &middot; Temp File Hosting                                                                   Info 			Github                                                                   Info 			Github                                                                                                                                   File uploaded!                     			http://a.uguu.se/nicqdy_tmp.lHRSOMEHTINGPG.png 			Your file will be available for download during 24 hours.                                                                                                           What is Uguu?                     Uguu lets you store file(s) up to 100MB for 24 hours. 		                                      Contact                                              @nekunekus                         neku@pomf.se

**Comment by jad340** [comment]
Fixed in #29

**Comment by Bestora** [comment]
new problem:

< html>
< head>< title>301 Moved Permanently< /title>< /head>
< body bgcolor="white">
< center>< h1>301 Moved Permanently< /h1>< /center>
< hr>< center>nginx</center>
< /body>
< /html>

**Comment by jschx** [comment]
Fixed! A big sorry to everyone for the breakage and lack of development.
