### ISSUE TITLE
-p option

### ISSUE THREAD

**Issue by BobbyWibowo** [jschx/uguush#36]
README claimed that it would save the files with format, but https://github.com/jschx/uguush/blob/master/uguush#L199 wouldn't really do so :thinking:

**Comment by BobbyWibowo** [comment]
Also I recently forked this and added some new options, mainly support for [lolisafe](https://github.com/WeebDev/lolisafe)-based hosts (although it defaults to my site, and changing the URL will still require manually editing the file).
Will you still review new PRs? I'll still have to make a new branch with changes tailored for master, since the changes I pushed to my fork's branch is tailored for personal usage (such as defaulting host to lolisafe), so I'd rather find out beforehand whether you'll still review them.

**Comment by jschx** [comment]
I'm not sure what you mean. It's intended for you to specify a path to which the script will save a timestamped screenshot. Is it not doing so?
Also, yes, I will absolutely review new PRs. I feel like the script is due for a cleanup one of these days, though. I've been mindlessly merging PRs here for quite a while and I'm afraid it's getting a little bloated.

**Comment by BobbyWibowo** [comment]
Yeah, the help message and the git README claimed that it would save timestamped screenshots to the path, but instead it would simply save them with the temp files' base name (you know, that tmp.blablabla thing).

I noticed that the PR which was supposed to add this feature (from a quick glimpse yesterday) would indeed save them with timestamp names, but latest master wouldn't (although I'm not sure in which commit in particular it got reversed).

**Comment by jschx** [comment]
Fixed in 290b17aff4d3c539af100ee8a68b8d06c4996de7.
